import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#1000a9",
        "outline-variant": "#464554",
        "on-tertiary": "#4f2500",
        tertiary: "#ffb783",
        "inverse-primary": "#494bd6",
        "surface-container": "#201f22",
        "error-container": "#93000a",
        "on-surface-variant": "#c7c4d7",
        "on-secondary-fixed-variant": "#5516be",
        "on-secondary-fixed": "#23005c",
        primary: "#c0c1ff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary": "#3c0091",
        "surface-container-lowest": "#0e0e10",
        background: "#131315",
        "primary-fixed-dim": "#c0c1ff",
        "surface-bright": "#39393b",
        "surface-dim": "#131315",
        "primary-container": "#8083ff",
        secondary: "#d0bcff",
        "on-surface": "#e5e1e4",
        "surface-variant": "#353437",
        "on-tertiary-container": "#452000",
        "tertiary-fixed": "#ffdcc5",
        "inverse-on-surface": "#313032",
        "inverse-surface": "#e5e1e4",
        surface: "#131315",
        "secondary-fixed": "#e9ddff",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#ffb783",
        "surface-container-low": "#1c1b1d",
        "on-tertiary-fixed": "#301400",
        "primary-fixed": "#e1e0ff",
        "on-secondary-container": "#c4abff",
        "surface-tint": "#c0c1ff",
        "surface-container-highest": "#353437",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "secondary-container": "#571bc1",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#07006c",
        "tertiary-container": "#d97721",
        "on-primary-container": "#0d0096",
        outline: "#908fa0",
        "surface-container-high": "#2a2a2c",
        "on-background": "#e5e1e4",
        "on-tertiary-fixed-variant": "#703700",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1rem",
        "stack-lg": "2rem",
        "container-max": "1280px",
        "stack-md": "1rem",
        "stack-sm": "0.5rem",
        gutter: "1.5rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-caps": ["var(--font-jetbrains-mono)", "monospace"],
        "stats-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "stats-lg": ["36px", { lineHeight: "1.0", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
